Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"

  # config.vm.box = "generic/centos8"

  # centos/8, work around to resolve C* error
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.no_remote = false
    config.vbguest.auto_update = false
  end

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

   # Customize the amount of memory on the VM:
    vb.memory = 8192
    vb.cpus = 4  
  end

  # config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "shell", path: "script.sh"
end
